# -*- coding: utf-8 -*-
import re
from lib.connection.response import BaseResponse

class WAF:
    # Pre-compile regexes for speed
    REGEX_CLOUDFLARE_BLOCK = re.compile(r"Attention Required! Cloudflare|security check to access|why have I been blocked|This website is using a security service|Cloudflare Ray ID", re.IGNORECASE)
    REGEX_APP_ERROR = re.compile(r"File not found|Error 403|The page you requested was not found|<title>.*Error.*</title>|<h2>Error 403: File not found</h2>", re.IGNORECASE)
    
    REGEX_AWS_BLOCK = re.compile(r"Request generated by CloudFront|Request token ID", re.IGNORECASE)
    REGEX_AWS_APP = re.compile(r"<Code>AccessDenied</Code>|The specified key does not exist|User is not authorized", re.IGNORECASE)
    
    REGEX_NGINX_STOCK = re.compile(r"<center>nginx</center>", re.IGNORECASE)
    REGEX_APACHE_STOCK = re.compile(r"Apache/[\d\.]+ Server at", re.IGNORECASE)
    
    REGEX_GENERIC_WAF = re.compile(r"Your access was blocked|Security incident detected", re.IGNORECASE)

    @staticmethod
    def analyze(response: BaseResponse) -> dict:
        result = {
            "source": "Unknown",
            "confidence": "Low",
            "trigger": None,
            "waf_present": False
        }
        
        # Prepare data
        headers = {k.lower(): v for k, v in response.headers.items()}
        body = ""
        if hasattr(response, "content") and response.content:
            body = response.content
        elif hasattr(response, "body") and response.body:
            body = response.body.decode('utf-8', errors='ignore')
            
        # ---------------------------------------------------------
        # 1. Cloudflare Logic
        # ---------------------------------------------------------
        is_cloudflare_infra = "cloudflare" in headers.get("server", "").lower() or "cf-ray" in headers

        if is_cloudflare_infra:
            result["waf_present"] = True
            
            if match := WAF.REGEX_CLOUDFLARE_BLOCK.search(body):
                 return {"source": "Cloudflare WAF", "confidence": "High", "trigger": f"Body: {match.group(0)}", "waf_present": True}
            
            if match := WAF.REGEX_APP_ERROR.search(body):
                 return {"source": "Cloudflare (App Logic)", "confidence": "High", "trigger": f"Body: {match.group(0)}", "waf_present": True}
            
            return {"source": "Cloudflare", "confidence": "Medium", "trigger": "Header: Server: cloudflare", "waf_present": True}

        # ---------------------------------------------------------
        # 2. AWS WAF / CloudFront Logic
        # ---------------------------------------------------------
        is_aws_infra = (
            "cloudfront" in headers.get("via", "").lower() or
            "x-amz-cf-id" in headers or
            "awselb" in headers.get("server", "").lower() or
            "x-amzn-errortype" in headers
        )

        if is_aws_infra:
            result["waf_present"] = True
            
            # True Block
            if headers.get("x-amzn-errortype") == "ForbiddenException" or WAF.REGEX_AWS_BLOCK.search(body):
                return {"source": "AWS WAF", "confidence": "High", "trigger": "AWS Block Signature", "waf_present": True}
            
            # App Logic
            if WAF.REGEX_AWS_APP.search(body):
                return {"source": "AWS (App Logic)", "confidence": "High", "trigger": "AWS App Signature", "waf_present": True}
            
            return {"source": "AWS/CloudFront", "confidence": "Medium", "trigger": "AWS Infrastructure Header", "waf_present": True}

        # ---------------------------------------------------------
        # 3. Nginx Logic
        # ---------------------------------------------------------
        if "nginx" in headers.get("server", "").lower():
            # True Block (Server Config)
            # Check for stock page signature OR plain text "403 Forbidden" in a short body
            if WAF.REGEX_NGINX_STOCK.search(body) or (len(body) < 200 and "403 forbidden" in body.lower()):
                 return {"source": "Nginx (Server Block)", "confidence": "High", "trigger": "Nginx Stock Page", "waf_present": False}
            
            # App Logic (Default if header is nginx but body is not stock)
            return {"source": "Nginx (App Logic)", "confidence": "Medium", "trigger": "Nginx Header + Custom Body", "waf_present": False}

        # ---------------------------------------------------------
        # 4. Apache Logic
        # ---------------------------------------------------------
        if "apache" in headers.get("server", "").lower():
             # True Block
             if WAF.REGEX_APACHE_STOCK.search(body) or (len(body) < 200 and "forbidden" in body.lower()):
                 return {"source": "Apache (Server Block)", "confidence": "High", "trigger": "Apache Stock Page", "waf_present": False}
             
             # App Logic
             return {"source": "Apache (App Logic)", "confidence": "Medium", "trigger": "Apache Header + Custom Body", "waf_present": False}

        # ---------------------------------------------------------
        # 5. Generic / Other WAFs
        # ---------------------------------------------------------
        if match := WAF.REGEX_GENERIC_WAF.search(body):
            return {"source": "Generic WAF", "confidence": "Medium", "trigger": f"Body: {match.group(0)}", "waf_present": True}

        if "x-cdn" in headers and "incapsula" in headers["x-cdn"].lower():
            return {"source": "Incapsula", "confidence": "High", "trigger": "Header: X-CDN: Incapsula", "waf_present": True}
            
        if "server" in headers:
            server = headers["server"].lower()
            if "iis" in server:
                return {"source": "IIS", "confidence": "High", "trigger": "Header: Server: iis", "waf_present": False}
            if "sucuri" in server:
                return {"source": "Sucuri", "confidence": "High", "trigger": "Header: Server: sucuri", "waf_present": True}
            if "akamai" in server:
                return {"source": "Akamai", "confidence": "High", "trigger": "Header: Server: akamai", "waf_present": True}

        return result

    @staticmethod
    def detect(response: BaseResponse) -> str | None:
        result = WAF.analyze(response)
        if result["source"] != "Unknown":
            return result["source"]
        return None
